helios-library-app/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author_Last_Name__c</fullName>
        <description>The last name of the first author on the book</description>
        <label>Author Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDN__c</fullName>
        <description>The numeric part of a Dewey Decimal Code.</description>
        <inlineHelpText>The Dewey Decimal Number WITHOUT any letters.</inlineHelpText>
        <label>Dewey Decimal Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Manual_Cutter_Code__c</fullName>
        <inlineHelpText>For books in locations requiring manual Cutter Code entry (such as biographies), enter a three letter code (in the case of biographies, usually the upper-case version of the first three letters of the subject&apos;s last name).</inlineHelpText>
        <label>Cutter Code</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Main_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Location</label>
        <referenceTo>Main_Location__c</referenceTo>
        <relationshipLabel>Sublocations</relationshipLabel>
        <relationshipName>Sublocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Main_Location__c.object
<CustomObject>
    <fields>
        <fullName>Uses_Dewey_Decimal_Coding__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If checked, this main location uses Dewey decimal coding--a Dewey decimal number plus a three-letter code--to identify books</inlineHelpText>
        <label>Uses Dewey Decimal Coding</label>
        <type>Checkbox</type>
    </fields>
    <label>Main Location</label>
    <nameField>
        <label>Main Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Main Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/classes/NewBookExtension.cls
public class NewBookExtension {
    public ApexPages.StandardController controller {public get; set;}
    public boolean useDDN {public get; set;}
	
    public NewBookExtension(ApexPages.StandardController controller) {
        this.controller = controller;
        if (useDDN != true) {
	        useDDN = false;
        	relocate();
        }
    }
    
    public PageReference doSaveOrFindExisting() {
        Book__c enteredBook = (Book__c) controller.getRecord();
        if (enteredBook.Id != null) {
            //This is an edit; just save it
            return validateAndSaveInternal();
        }
        String title = enteredBook.Title__c;
        String authorLastName = enteredBook.Author_Last_Name__c;
        Book__c[] existingBooks;
        if (String.isBlank(authorLastName)) {
            existingBooks = [SELECT id from Book__c where Title__c = :title];
        } else {
            existingBooks = [SELECT id from Book__c where Title__c = :title and Author_Last_Name__c = :authorLastName];
        }
        if (existingBooks.size() > 0) {
            PageReference newBookCopy = Page.newBookCopy;
        	newBookCopy.getParameters().put('bookId', existingBooks[0].id);
        	return newBookCopy;
        } else {
            return validateAndSaveInternal();
        }
    }
    
    //For now, we don't want this in a trigger, because import can't set the DDN yet.
    PageReference validateandSaveInternal() {
        relocate();
        if (useDDN) {
            Book__c book = (Book__c) controller.getRecord();
            if (String.isBlank(book.DDN__c)) {
                book.DDN__c.addError('A dewey decimal number is required for a book in this location');
                return null;
            } 
        }
        return controller.save();
    }
    
    public PageReference relocate() {
        Book__c book = (Book__c) controller.getRecord();
        Id locId = book.location__c;
        boolean wasUseDDN = useDDN;
        if (book.Location__c != null) {
        	Location__c loc = [SELECT main_location__r.Uses_Dewey_Decimal_Coding__c from location__c where id=:locId];
        	useDDN = loc.main_location__r.Uses_Dewey_Decimal_Coding__c;
        }
        if (wasUseDDN && !useDDN) {
            book.DDN__c = null;
            book.Manual_Cutter_Code__c = null;
        }
        return null;
    }
}