helios-library-app/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author_Display_Name__c</fullName>
        <formula>Author_Last_Name__c  &amp;   IF(! ISBLANK( Author_First_Name__c) , &apos;, &apos; &amp;  Author_First_Name__c, &apos;&apos;)</formula>
        <label>Author</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Waitlist_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>Book__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Waitlist Entry</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Waitlist Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/WaitlistEntryExtension.cls
public class WaitlistEntryExtension {
    public Book__c theBook {public get; private set;}
    public WaitlistEntryExtension(ApexPages.StandardController controller) {
        Waitlist_Entry__c record = (Waitlist_Entry__c) controller.getRecord();
        record.Book__c = ApexPages.currentPage().getParameters().get('bookId');
        theBook = [select Title__c, Author_Display_Name__c from Book__c where Id = :record.Book__c];
    }
    
    
}