helios-library-app/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author_First_Name__c</fullName>
        <label>Author First Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Author_Last_Name__c</fullName>
        <description>The last name of the first author on the book</description>
        <label>Author Last Name</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copyright_Date__c</fullName>
        <label>Publication Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DDN__c</fullName>
        <description>The numeric part of a Dewey Decimal Code.</description>
        <inlineHelpText>The Dewey Decimal Number WITHOUT any letters.</inlineHelpText>
        <label>Dewey Decimal Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ISBN__c</fullName>
        <label>ISBN</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newberry_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newbery Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <inlineHelpText>A brief summary of the book</inlineHelpText>
        <label>Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Book_Copy__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Copies_of_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Copy of Book</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies of Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Location__c.object
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Waitlist_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>Book__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Waitlist Entry</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Waitlist Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/DedupeBooksBatch.cls
global class DedupeBooksBatch implements Database.Batchable<AggregateResult> {
    global Iterable<AggregateResult> start(Database.BatchableContext BC) {
        return new AggregateResultIterable(
            'SELECT min(id), name, title__c, author_last_name__c, author_first_name__c ' +
            'FROM Book__c ' + 
            'GROUP BY name, title__c, author_last_name__c, author_first_name__c ' +
            'HAVING count(id) > 1');
    }
    
    global void execute(Database.BatchableContext BC, List<Sobject> scope) {
        for (SObject res : scope) {
            Book__c[] dups = [SELECT id,
                              DDN__c,
                              ISBN__c,
                              Location__c,
                              Newberry_Book__c,
                              Copyright_Date__c,
                              Summary__c,
                              (SELECT id,
                              Book__c from
                              Copies_of_books__r),
                              (select id,
                              Book__c from waitlist__r)
                              from Book__c where 
                        name = :(String)res.get('name') and
                        title__c = :(String)res.get('title__c') and
                        author_last_name__c = :(String)res.get('author_last_name__c') and
                        author_first_name__c = :(String)res.get('author_first_name__c')];
            Book__c master = dups[0];
            List<Book_Copy__c> copiesToUpdate = new List<Book_Copy__c>();
            List<Waitlist_Entry__c> waitlistsToUpdate = new List<Waitlist_Entry__c>();
            List<Book__c> booksToDelete = new List<Book__c>();
            //Start with 1, since 0 is the master
            for (Integer i=1; i < dups.size(); i++) {
                Book__c dup = dups[i];
                booksToDelete.add(dup);
                if (dup.DDN__c != null && (master.DDN__c == null || master.DDN__c < dup.DDN__c)) {
                    master.DDN__c = dup.DDN__c;
                }
                if (dup.ISBN__c != null && !dup.ISBN__c.startsWith('X') && 
                    (master.ISBN__c == null || master.ISBN__c.startsWith('X'))) {
                        master.ISBN__c = dup.ISBN__c;
                    }
                if (master.Location__c == null && dup.Location__c != null) {
                    master.Location__c = dup.Location__c;
                }
                if (dup.Newberry_Book__c) {
                    master.Newberry_Book__c = true;
                }
                if (dup.Copyright_Date__c != null && (master.Copyright_Date__c == null || master.Copyright_Date__c > dup.Copyright_Date__c)) {
                    master.Copyright_Date__c = dup.Copyright_Date__c;
                }
                if (dup.Summary__c != null && (master.Summary__c == null || master.Summary__c.length() < dup.Summary__c.length())) {
                    master.Summary__c = dup.Summary__c;
                }
                if (dup.copies_of_books__r != null) {
                    for (Book_copy__c copy : dup.Copies_of_books__r) {
                        copy.book__c = master.id;
                        copiesToUpdate.add(copy);
                    }
                }
                if (dup.Waitlist__r != null) {
                    for (Waitlist_entry__c waitlist : dup.Waitlist__r) {
                        waitlist.book__c = master.id;
                        waitlistsToUpdate.add(waitlist);
                    }
                }
            }
            update master;
            update copiesToUpdate;
            update waitlistsToUpdate;
            delete booksToDelete;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
}