helios-library-app/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Book_Copy__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Copies_of_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Copy of Book</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies of Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/NewBookCopyControllerTest.cls
@IsTest
public class NewBookCopyControllerTest {
    public static testmethod void testSaveCopy() {
        Book__c newBook = ApexTestUtil.createTestBook('XXXXXXXXXXX');
        //May not be 0 if we have autocreate
        integer oldcopies = [SELECT COUNT() from Book_copy__c where book__c = :newBook.Id];
        PageReference pageRef = Page.newbookcopy;
        pageRef.getParameters().put('bookId', newBook.Id);
        Test.setCurrentPage(pageRef);
        NewBookCopyController controller = new NewBookCopyController();
        pageRef = controller.save();
        PageReference expectedResult = Page.book;
        expectedResult.getParameters().put('id', newBook.Id);
        System.assertEquals(expectedResult.getUrl(), pageRef.getUrl());
        integer newCopies = [SELECT COUNT() from Book_copy__c where book__c = :newBook.Id];
        System.assertEquals(newCopies, oldCopies + 1);
    }
}