helios-library-app/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Waitlist_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Waitlist Entry</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Waitlist Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/WaitlistEntryExtensionTest.cls
@IsTest
public class WaitlistEntryExtensionTest {
    public static testmethod void testNewWaitlist() {
        Book__c theBook = ApexTestUtil.createTestBook('Test Book');
        PageReference waitlistEntryPage = Page.NewWaitlistEntry;
        waitlistEntryPage.getParameters().put('bookId', theBook.Id);
        Test.setCurrentPage(waitlistEntryPage);
        ApexPages.StandardController ctrlr = new ApexPages.StandardController(new Waitlist_Entry__c());
        WaitlistEntryExtension ext = new WaitlistEntryExtension(ctrlr);
        System.assertEquals(theBook.Id, ((Waitlist_Entry__c) ctrlr.getRecord()).Book__c);
    }
}