helios-library-app/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Main_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Location</label>
        <referenceTo>Main_Location__c</referenceTo>
        <relationshipLabel>Sublocations</relationshipLabel>
        <relationshipName>Sublocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Main_Location__c.object
<CustomObject>
    <label>Main Location</label>
    <nameField>
        <label>Main Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Main Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/classes/ConsolidateNonfictionBatch.cls
global class ConsolidateNonfictionBatch implements Database.Batchable<sObject> {
    Id nonFictionLocId {get; set;}
    boolean hasErrors {get; set;}
    
    public ConsolidateNonfictionBatch() {
        Location__c properLoc = [SELECT ID from Location__c where Name = 'Non-Fiction' and Main_Location__r.Name ='Non-Fiction'];
        nonFictionLocId = properLoc.Id;
        hasErrors = false;
    }
    
    global Database.QueryLocator start(Database.BatchableContext ctx) {
        return Database.getQueryLocator('SELECT Location__c from Book__c ' + 
                                        'WHERE Location__r.Name != \'Non-Fiction\' AND Location__r.Main_Location__r.Name = \'Non-Fiction\''
                 );
    }
    
    global void execute(Database.BatchableContext ctx, List<Sobject> books) {
        for (SObject book : books) {
            book.put(Book__c.fields.Location__c, nonFictionLocId);
        }
        try {
            update books;
        } catch (System.DmlException e) {
            this.hasErrors = true;
            throw e;
        }
        
    }
    
    global void finish(Database.BatchableContext ctx) {
        if (!this.hasErrors) {
            Location__c[] toDelete = [SELECT Id from Location__c WHERE Name != 'Non-Fiction' AND Main_Location__r.Name = 'Non-Fiction'];
            delete toDelete;
        }
    }
}