helios-library-app/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author_Display_Name__c</fullName>
        <formula>Author_Last_Name__c  &amp;   IF(! ISBLANK( Author_First_Name__c) , &apos;, &apos; &amp;  Author_First_Name__c, &apos;&apos;)</formula>
        <label>Author</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Book_Copy__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Copies_of_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Copy of Book</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies of Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/NewBookCopyController.cls
public class NewBookCopyController {
  public Book_copy__c newCopy {public get; public set;}
  
  public NewBookCopyController() {
     newCopy = new Book_Copy__c();
     newCopy.book__c = ApexPages.currentPage().getParameters().get('bookId');
     newCopy.book__r = [SELECT id, title__c, Author_Display_Name__c from book__c where id = :newCopy.book__c];
  }
  
  public PageReference save() {
      insert newCopy;
      return returnToBook();
  }
  
  public PageReference cancel() {
      return returnToBook();
  }
  
  private PageReference returnToBook() {
      PageReference bookret = Page.Book;
      bookret.getParameters().put('id', newCopy.book__c);
      return bookret;
  }
}