helios-library-app/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>ISBN__c</fullName>
        <label>ISBN</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Book_Copy__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Copies_of_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Waiting_Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Waiting On Copy</label>
        <referenceTo>Waitlist_Entry__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Waiting_On</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Copy of Book</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies of Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Checkout__c.object
<CustomObject>
    <fields>
        <fullName>Book_Copy__c</fullName>
        <label>Book</label>
        <referenceTo>Book_Copy__c</referenceTo>
        <relationshipLabel>Checkouts</relationshipLabel>
        <relationshipName>Checkouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Checkouts</relationshipLabel>
        <relationshipName>Checkouts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Checkout</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Checkout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checkouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Main_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Location</label>
        <referenceTo>Main_Location__c</referenceTo>
        <relationshipLabel>Sublocations</relationshipLabel>
        <relationshipName>Sublocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Main_Location__c.object
<CustomObject>
    <label>Main Location</label>
    <nameField>
        <label>Main Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Main Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Waitlist_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Notified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>Book__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Waitlist Entry</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Waitlist Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/ApexTestUtil.cls
@isTest
public class ApexTestUtil {

    public static User getSeeker() {
        User seeker = [SELECT id from User where profile.name='Seeker' limit 1];
        return seeker;
    }
    
    public static User getLibrarian() {
        User librarian = [SELECT id from User where profile.name='Librarian' limit 1];
        return librarian;
    }
    
    public static Contact createTestStudent(String lastName) {
        Account testAccount = new Account();
        testAccount.name = 'TestAcc';
        insert testAccount;
        Contact testStudent = new Contact();
        testStudent.lastName = lastName;
        insert testStudent;
        return testStudent;
    }
    
    public static Book__c createTestBook(String title) {
        Book__c testBook = new Book__c();
        //testBook.ISBN__c = 'XXX' + title.leftPad(10, 'X').substring(0,10);
        testBook.title__c = title;
        insert testBook;
        return testBook;
    }
    
    public static Waitlist_entry__c createWaitlistEntry(Contact student, Book__c book) {
        Waitlist_entry__c entry = new Waitlist_entry__c();
        entry.book__c = book.id;
        entry.student__c = student.id;
        entry.status__c = 'Waiting';
        insert entry;
        return entry;
    }
    
    public static void notifyWaitlistForCopy(Waitlist_entry__c waitlist, book_copy__c copy) {
        waitlist.status__c = 'Notified';
        copy.waiting_student__c = waitlist.id;
        update waitlist;
        update copy;
    }
    
    public static Book_copy__c createTestBookCopy(Book__c book) {
        Book_copy__c copy = new Book_copy__c();
        copy.book__c = book.id;
        insert copy;
        return copy;
    }
    
    public static Checkout__c createCheckout(Book_copy__c copy, Contact student) {
        Checkout__c checkout = new Checkout__c();
        checkout.book_copy__c = copy.id;
        checkout.student__c = student.id;
        insert checkout;
        return checkout;
    }
    
    public static Main_Location__c createMainLocation(String name) {
        Main_Location__c mainLocation = new Main_Location__c();
        mainLocation.name = name;
        insert mainLocation;
        return mainLocation;
    }
    
    public static Location__c createLocation(String name, Main_Location__c parent) {
        Location__c location = new Location__c();
        location.name = name;
        location.Main_Location__c = parent.id;
        insert location;
        return location;
    }
}