helios-library-app/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author_Display_Name__c</fullName>
        <formula>Author_Last_Name__c  &amp;   IF(! ISBLANK( Author_First_Name__c) , &apos;, &apos; &amp;  Author_First_Name__c, &apos;&apos;)</formula>
        <label>Author</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Copyright_Date__c</fullName>
        <label>Publication Year</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dewey_Decimal_Code__c</fullName>
        <formula>IF( Location__r.Main_Location__r.Uses_Dewey_Decimal_Coding__c,
    IF(  ISBLANK(Manual_Cutter_Code__c)  , 
         DDN__c  &amp; &apos; &apos; &amp;  LEFT(UPPER( Author_Last_Name__c) , 3),
         DDN__c &amp; &apos; &apos; &amp; UPPER( Manual_Cutter_Code__c )
    ),
    null
)</formula>
        <label>Dewey Decimal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Generally_Available_Copies__c</fullName>
        <formula>Available_Copies__c -  Copies_On_Hold__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>The number of copies of the book available (not checked out or on hold)</inlineHelpText>
        <label>Generally Available Copies</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Location</label>
        <referenceTo>Location__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Newberry_Book__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Newbery Book</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Book_Copy__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Copies_of_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Copy_Number__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>ID#</label>
        <type>AutoNumber</type>
    </fields>
    <label>Copy of Book</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies of Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Full_Location__c</fullName>
        <formula>Main_Location__r.Name &amp; &quot; - &quot; &amp; Name</formula>
        <label>Full Location</label>
        <type>Text</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/classes/BookSearchController.cls
public class BookSearchController {
    public String searchTerms {public get; public set;}
    public String copyNum {public get; public set;}
    
    public ApexPages.StandardSetController booksController {public get; private set;}
    public Book__c[] books {public get; private set;}
    
    public ApexPages.PageReference doSearch() {
         if (String.isBlank(searchTerms)) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                                                       'Please enter at least one search term.')
                                 );
            return null;
        }
        List<List<SObject>> results = [FIND :searchTerms IN ALL FIELDS RETURNING 
                                       Book__c(Id, Title__c, Author_display_name__c, Copyright_Date__c,
                                              Location__r.Full_Location__c, Dewey_Decimal_Code__c,
                                               Generally_Available_Copies__c, Newberry_Book__c)];
        books = results[0];
        booksController = new ApexPages.StandardSetController(books);
        return null;
    }
    
    public ApexPages.PageReference goToBook() {
        if (String.isBlank(copyNum)) {
           ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                                                       'Please enter a copy number.')
                                 );
            return null;
        }
        Book_copy__c[] copies = [Select Book__c from Book_Copy__c where Copy_Number__c = :copyNum];
        if (copies.size() == 0) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,
                                                       'No book copy with that number.')
                                 );
            return null;
        }
        
        System.assertEquals(copies.size(), 1, 'Duplicate copy number found');
        Id bookId = copies[0].Book__c;
        ApexPages.PageReference target =Page.Book;
        target.getParameters().put('id', bookId);
        return target;
    }
    
}