helios-library-app/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Waitlist_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Waitlist Entry</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Waitlist Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/ApexTests.cls
@IsTest public class ApexTests {

    /* Ensure you can add a student without specifying an account */
    static testmethod void testSetAccountTrigger() {
        createTestStudent();
    } 
    /*
    static testmethod void testCheckExistingWaitlist() {
        Contact student = createTestStudent();
        Book__c book = createTestBook();
        createWaitlistEntry(student, book);
        try {
            createWaitlistEntry(student, book);
            System.assert(false, 'able to create duplicate waitlist entry');
        } catch (DmlException e) {
            //expected result
        }
    } */
    
    private static Contact createTestStudent() {
        Contact testStudent = new Contact();
        testStudent.lastName = 'testStudentLastName';
        insert testStudent;
        return testStudent;
    }
    /*
    private static Book__c createTestBook() {
        Book__c testBook = new Book__c();
        testBook.name = 'testIsbn';
        insert testBook;
        return testBook;
    }

    private static Waitlist_entry__c createWaitlistEntry(Contact student, Book__c book) {
        Waitlist_entry__c entry = new Waitlist_entry__c();
        entry.book__c = book.id;
        entry.student__c = student.id;
        insert entry;
        return entry;
    } */
}