helios-library-app/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Book_Copy__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Copies_of_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Copy_Number__c</fullName>
        <displayFormat>{000000}</displayFormat>
        <externalId>true</externalId>
        <label>ID#</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Donated_By__c</fullName>
        <inlineHelpText>You can leave this field blank if there is no identified donor.</inlineHelpText>
        <label>Donated By</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Permanent_Status__c</fullName>
        <inlineHelpText>The permanet status of this book copy.</inlineHelpText>
        <label>Deletion Reason</label>
        <picklist>
            <picklistValues>
                <fullName>Reported Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Missing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Destroyed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Removed from Collection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Erroneous Entry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>St_Martin__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Does this book belong to the St. Martin&apos;s collection?</inlineHelpText>
        <label>St. Martin&apos;s Collection</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Waiting_Student__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Student Waiting On Copy</label>
        <referenceTo>Waitlist_Entry__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Waiting_On</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Copy of Book</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies of Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Checkout__c.object
<CustomObject>
    <fields>
        <fullName>Book_Copy__c</fullName>
        <label>Book</label>
        <referenceTo>Book_Copy__c</referenceTo>
        <relationshipLabel>Checkouts</relationshipLabel>
        <relationshipName>Checkouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether this checkout is currently active.</inlineHelpText>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Checkouts</relationshipLabel>
        <relationshipName>Checkouts</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Times_Renewed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Times Renewed</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Checkout</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Checkout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checkouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Waitlist_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Notified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Student__c</fullName>
        <label>Student</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Wait_Time__c</fullName>
        <formula>NULLVALUE( Date_Notified__c ,  TODAY() )  -  DATEVALUE(CreatedDate)</formula>
        <label>Wait Time</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Waitlist Entry</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Waitlist Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/BookExtension.cls
public class BookExtension{
    public Book_Copy__c[] copies {public get; set;}
    public Waitlist_Entry__c[] extraWaitlist {public get; set;}
    
    public BookExtension(ApexPages.StandardController controller) {
        Id bookId = controller.getId();
        copies = [SELECT Id, St_Martin__c, Copy_Number__c, Donated_By__c,
                  Waiting_Student__c, Waiting_Student__r.Student__c, Waiting_Student__r.Student__r.Name, 
                  (SELECT Id, Times_renewed__c, Student__c, Student__r.Name FROM Checkouts__r WHERE is_current__c=true LIMIT 1) 
                  FROM Book_Copy__c
                  WHERE  Book__c=:bookId and Permanent_Status__c = null];
        extraWaitlist = [Select Id, Student__c, Student__r.Name, Wait_Time__c  
                         FROM Waitlist_Entry__c 
                         WHERE Status__c='Waiting' AND Book__c=:bookId];
    }
    
    public PageReference checkIn() {
        Checkout__c checkout = [SELECT Id, is_current__c FROM Checkout__c WHERE book_copy__c = :ApexPages.currentPage().getParameters().get('copyId') and is_current__c = true];
        checkout.Is_Current__c = false;
        update checkout;
        ApexPages.currentPage().setRedirect(true);
        return ApexPages.currentPage();
    }
    
    public PageReference renew() {
        Checkout__c checkout = [SELECT Id, Times_Renewed__c, Book_Copy__c, Student__c FROM Checkout__c WHERE book_copy__c = :ApexPages.currentPage().getParameters().get('copyId') and is_current__c = true];
        
        Checkout__c newCheckout = checkout.clone();
        newCheckout.Times_Renewed__c = checkout.Times_Renewed__c + 1;
        checkout.Is_Current__c = false;
        update checkout;
        insert newCheckout;
        ApexPages.currentPage().setRedirect(true);
        return ApexPages.currentPage();
    }
    
    public PageReference checkOutForReserved() {
        return WaitlistUtil.checkOutForWaitlist(ApexPages.currentPage().getParameters().get('copyId'));
    }
    

}