helios-library-app/src/objects/Book__c.object
<CustomObject>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Book_Copy__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Copies_of_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Copy of Book</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies of Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Checkout__c.object
<CustomObject>
    <fields>
        <fullName>Book_Copy__c</fullName>
        <label>Book</label>
        <referenceTo>Book_Copy__c</referenceTo>
        <relationshipLabel>Checkouts</relationshipLabel>
        <relationshipName>Checkouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether this checkout is currently active.</inlineHelpText>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <label>Checkout</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Checkout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checkouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/BookExtensionTest.cls
@IsTest
public class BookExtensionTest {
    public static testmethod void testCheckout() {
        Contact student = ApexTestUtil.createTestStudent('BookExtensionStudent');
        Book__c book = ApexTestUtil.createTestBook('xxxxxxxxxxxxx');
        Book_copy__c copy = ApexTestUtil.createTestBookCopy(book);
        Checkout__c checkout = ApexTestUtil.createCheckout(copy, student);
        checkout = [select is_current__c from checkout__c where id=:checkout.Id];
        System.assert(checkout.Is_Current__c);
        PageReference pageRef = Page.Book;
        pageRef.getParameters().put('id', book.id);
        pageRef.getParameters().put('copyId', copy.id);
        Test.setCurrentPage(pageRef);
        BookExtension ext = new BookExtension(new ApexPages.StandardController(book));
        pageRef = ext.checkIn();
        checkout = [select is_current__c from checkout__c where id=:checkout.Id];
        System.assert(!checkout.Is_Current__c);
    }
}