helios-library-app/src/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>ISBN__c</fullName>
        <label>ISBN</label>
        <length>13</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Book_Copy__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Copies of Books</relationshipLabel>
        <relationshipName>Copies_of_Books</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Copy of Book</label>
    <nameField>
        <displayFormat>B-{00000}</displayFormat>
        <label>Copy Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Copies of Books</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Checkout__c.object
<CustomObject>
    <fields>
        <fullName>Book_Copy__c</fullName>
        <label>Book</label>
        <referenceTo>Book_Copy__c</referenceTo>
        <relationshipLabel>Checkouts</relationshipLabel>
        <relationshipName>Checkouts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Is_Current__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Whether this checkout is currently active.</inlineHelpText>
        <label>Is Current</label>
        <type>Checkbox</type>
    </fields>
    <label>Checkout</label>
    <nameField>
        <displayFormat>C-{000000}</displayFormat>
        <label>Checkout Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Checkouts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/objects/Waitlist_Entry__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipName>Waitlist</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Waiting</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Notified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfilled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expired</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>Book__r.Title__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <label>Waitlist Entry</label>
    <nameField>
        <displayFormat>W-{000000}</displayFormat>
        <label>Waitlist Entry Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Waitlist</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

helios-library-app/src/classes/ApexTriggerTests.cls
@isTest
public class ApexTriggerTests {

    /* Ensure you can add a student without specifying an account */
    static testmethod void testSetAccountTrigger() {
        ApexTestUtil.createTestStudent('testSetAccountTriggerStudent');
    }
    
    static testmethod void testCheckExistingWaitlist() {
        Contact student = ApexTestUtil.createTestStudent('testCheckExistingWaitlistStudent');
        Book__c book = ApexTestUtil.createTestBook('testCheckExistingWaitlistBook');
        ApexTestUtil.createWaitlistEntry(student, book);
        try {
            ApexTestUtil.createWaitlistEntry(student, book);
            System.assert(false, 'able to create duplicate waitlist entry');
        } catch (DmlException e) {
            //expected result
        }
    }
    
    static testmethod void testCheckExistingCheckoutForWaitlist() {
        Contact student = ApexTestUtil.createTestStudent('testCheckExistingCheckoutStudent');
        Book__c book = ApexTestUtil.createTestBook('testCheckExistingCheckoutBook');
        Book_copy__c bookCopy = ApexTestUtil.createTestBookCopy(book);
        Checkout__c checkout = ApexTestUtil.createCheckout(bookCopy, student);
        try {
            ApexTestUtil.createWaitlistEntry(student, book);
            System.assert(false, 'able to create duplicate checkout');
         } catch (DmlException e) {
             //expected result
         }
    }
    
    static testmethod void testCheckDuplicateCheckout() {
        Contact student = ApexTestUtil.createTestStudent('testCheckExistingCheckoutStudent');
        Book__c book = ApexTestUtil.createTestBook('testCheckExistingCheckoutBook');
        Book_copy__c bookCopy1 = ApexTestUtil.createTestBookCopy(book);
        Book_copy__c bookCopy2 = ApexTestUtil.createTestBookCopy(book);
        Checkout__c checkout = ApexTestUtil.createCheckout(bookCopy1, student);
        try {
            ApexTestUtil.createCheckout(bookCopy2, student);
            System.assert(false, 'able to create duplicate checkout');
         } catch (DmlException e) {
             //expected result
         }
    }
    
    static testmethod void testWaitlistExpires() {
        Contact student1 = ApexTestUtil.createTestStudent('testWaitlistExpiresStudent1');
        Contact student2 = ApexTestUtil.createTestStudent('testWaitlistExpiresStudent2');
        Book__c book = ApexTestUtil.createTestBook('testWaitlistExpiresBook');
        Book_copy__c bookCopy = ApexTestUtil.createTestBookCopy(book);
        waitlist_entry__c firstWaitlistEntry = ApexTestUtil.createWaitlistEntry(student1, book);
        waitlist_entry__c secondWaitlistEntry = ApexTestUtil.createWaitlistEntry(student2, book);
        ApexTestUtil.notifyWaitlistForCopy(firstWaitlistEntry, bookCopy);
        firstWaitlistEntry.status__c = 'Expired';
        update firstWaitlistEntry;
        secondWaitlistEntry = [SELECT id, status__c from Waitlist_entry__c where id = :secondWaitlistEntry.id];
        System.assert(secondWaitlistEntry.status__c == 'Notified');
    }
    
    static testmethod void testNotifyOnCheckin() {
        Contact student1 = ApexTestUtil.createTestStudent('testWaitlistExpiresStudent1');
        Contact student2 = ApexTestUtil.createTestStudent('testWaitlistExpiresStudent2');
        Book__c book = ApexTestUtil.createTestBook('testWaitlistExpiresBook');
        Book_copy__c bookCopy = ApexTestUtil.createTestBookCopy(book);
        Checkout__c checkout = ApexTestUtil.createCheckout(bookCopy, student1);
        Waitlist_entry__c waitlistEntry = ApexTestUtil.createWaitlistEntry(student2, book);
        checkout.is_current__c = false;
        update checkout;
        waitlistEntry = [SELECT id, status__c from Waitlist_entry__c where id = :waitlistEntry.id];
        System.assert(waitlistEntry.status__c == 'Notified');
    }
    
    static testmethod void testTitleToName() {
        Book__c book = new Book__c();
        book.Title__c = 'Foo';
        book.Isbn__c = 'XXXXXXX';
        insert book;
        book = [SELECT Title__c, Name, isbn__c from book__c where id = :book.id];
        System.assertEquals(book.Name, 'Foo');
        System.assertEquals(book.ISBN__c, 'XXXXXXX');
        System.assertEquals(book.Title__c, 'Foo');
    }
}