helios-library-app/src/objects/Location__c.object
<CustomObject>
    <fields>
        <fullName>Check_Out_Allowed__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Can students check books out of this location?</description>
        <inlineHelpText>Can students check books out of this location?</inlineHelpText>
        <label>Check-Out Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Main_Location__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Main Location</label>
        <referenceTo>Main_Location__c</referenceTo>
        <relationshipLabel>Sublocations</relationshipLabel>
        <relationshipName>Sublocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/objects/Main_Location__c.object
<CustomObject>
    <label>Main Location</label>
    <nameField>
        <label>Main Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Main Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

helios-library-app/src/classes/EditLocationController.cls
public class EditLocationController {

    public Location__c location {public get; public set;}

    public EditLocationController() {
        Map<String, String> parameters = ApexPages.currentPage().getParameters();
        if (parameters.get('id') != null) {
            location = [select id, name, Check_Out_Allowed__c, main_location__r.name from location__c where id = :parameters.get('id')];
        } else {
           location = new Location__c();
           location.main_location__r = [SELECT id, name from main_location__c where id = :parameters.get('mainLocId')];
           location.main_location__c = parameters.get('mainLocId');
        }
    }
    
    public PageReference doSave() {
        upsert location;
        return Page.locations;
    }
    
        public PageReference cancel() {
        return Page.locations;
    }
}